language: ruby
sudo: false
cache: bundler

# Bundler/RubyGems incompat on Ruby 2.5.0
before_install: gem install bundler

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
